### ISSUE TITLE
cannot find arxiv paper from the given link

### ISSUE THREAD

**Issue by vd001** [hujie-frank/SENet#1]
cannot find arxiv paper from the given link

**Comment by hujie-frank** [comment]
Thank you for your attention to our work. We will release arxiv paper within one or two days.

**Comment by 1wy** [comment]
I'm looking forward to your paper. I want to see it as quickly as possible.

**Comment by liuguoyou** [comment]
looking forward to your paper

**Comment by youngwanLEE** [comment]
looking forward to your paper,too.

**Comment by acgtyrant** [comment]
I am looking forward to your paper too.

**Comment by rexnxiaobai** [comment]
looking forward to your paper, too.

**Comment by ArrowLuo** [comment]
looking forward to your paper, too.

**Comment by ppwwyyxx** [comment]
https://arxiv.org/pdf/1709.01507.pdf

**Comment by hujie-frank** [comment]
Hi, everyone. Our arxiv paper is released and the arxiv link is updated. Thank you for your attention to our work.
