### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by liu666666** [hujie-frank/SENet#10]
When I train the SE-ResNeXt-101 (32 x 4d), everything is ok. However, I train the SENet, the logs say that "status == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR". I disable CUDNN in the Makefile and recompile the caffe ,the error disappears. Without CUDNN, training the SENet is slower. Could you please tell me how to debug the error while using the CUDNN to accelerate the training?

**Comment by hujie-frank** [comment]
Which version of CuDNN do you use? Maybe you could try  CuDNN_v5 where I haven't met the crash.

**Comment by xiaoxiongli** [comment]
@hujie-frank   cudnn6.0 will met this issue,  but cudnn5.1  is ok,  so i use cudnn5.1 now, thank you~
