### ISSUE TITLE
What is the "Scale" ?

### ISSUE THREAD

**Issue by taki0112** [hujie-frank/SENet#11]
I'm implementing your network in tensorflow, but I do not know exactly what the scale is.

Can you explain ?
thank you

**Comment by hujie-frank** [comment]
The "Scale" operation is a channel-wise multiplication that one weight value corresponds to one feature map. You can find specific formula in our arXiv paper. FYI, [here](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet-se.py) is a third-party re-implementation in TenserFlow.
