### ISSUE TITLE
mean value and use_global_stats

### ISSUE THREAD

**Issue by sunformoon** [hujie-frank/SENet#13]
Hi Frank,

Good job! I have two puzzles to check with you. :)
1) The BatchNorm layer has "use_global_stats: true", which means the prototxt is the deploy instead of the train prototxt? Cuase if my understanding is correct, the use_global_stats is set to be **FALSE** during the training process of BN.

2) You comment the mean value in the prototxt. Does it mean that we need to minus the mean by myself cause it is possibly the deploy.prototxt?

Thank you!

Best,
Jordan

**Comment by hujie-frank** [comment]
Hi Jordan
    1. All of these are deploy prototxts. In order to convert to train prototxts,  you could insert weights initialization ("msra"), set lr_mult and decay_mult, and set use_global_stats  to be FALSE.
    2. The comment  shows what mean values we used in training as it is a deploy.prototxt.
