### ISSUE TITLE
Why use 1*1 convolution layer instead of full connect layer in SENet？For the less parameter？

### ISSUE THREAD

**Issue by miraclewkf** [hujie-frank/SENet#16]
Why use 1*1 convolution layer instead of full connect layer in SENet？For the less parameter？

**Comment by hujie-frank** [comment]
In fact, the 1*1 convolution layer is equivalent to fc layer here as the input spatial dimension is squeezed to 1*1.

**Comment by miraclewkf** [comment]
So the reason is not to reduce the amount of parameter? A fc layer has C*C/r parameters, but a 1*1 convolution layer only has C/r parameters.

**Comment by hujie-frank** [comment]
As for 1x1 convolutional layer whose input spatial dimension is 1x1, the amount of parameters you calculated is wrong.  
A 1x1 convolutional kernel has C parameters, so a 1x1 convolutional layer which comprises C/r convolutional kernels has CC/r paramters in total, matching the corresponding fc layer whose output number is C/r.
