### ISSUE TITLE
About Pooling_layer.cu

### ISSUE THREAD

**Issue by tianboguangding** [hujie-frank/SENet#18]
Hi，thanks for your shared code.
i have a question in pooling_layer.cu, a part of code is as followed:

......
......
case PoolingParameter_PoolMethod_AVE:
    if (this->layer_param_.pooling_param().global_pooling()) {
      // NOLINT_NEXT_LINE(whitespace/operators)
      GlobalAvePoolForward<Dtype><<<bottom[0]->count(0, 2), CAFFE_CUDA_NUM_THREADS>>>(
          bottom[0]->count(2), bottom_data, top_data);
    } else { 
      // NOLINT_NEXT_LINE(whitespace/operators)
      AvePoolForward<Dtype><<<CAFFE_GET_BLOCKS(count), CAFFE_CUDA_NUM_THREADS>>>(
          count, bottom_data, bottom[0]->num(), channels_,
          height_, width_, pooled_height_, pooled_width_, kernel_h_,
          kernel_w_, stride_h_, stride_w_, pad_h_, pad_w_, top_data);
    }
    break;
......
......
Sorry，Is it necessary to choose the void of GlobalAvePoolForward ？
And What is the difference between GlobalAvePoolForward  and AvePoolForward for the result?
Thank you！

**Comment by hujie-frank** [comment]
There are no differences between GlobalAvePoolForward and AvePoolForward while using global average pooling except that the former implemented by us is more efficiency.
