### ISSUE TITLE
About axpy_layer.cu

### ISSUE THREAD

**Issue by haoLiu1990** [hujie-frank/SENet#19]
Hi，thanks for your shared code.

48  for (int i = blockDim.x / 2; i > 0; i >>= 1) {
49   if (tid < i) {
50      buffer[threadIdx.x] += buffer[threadIdx.x + i];
51   }
52    __syncthreads();
53 }

Sorry, can you explain the logic behind lines from 48 to 53 in axpy_layer.cu? In my opinion, these piece of code should be commented out.

**Comment by hujie-frank** [comment]
The AxpyLayer is consists of channel-wise multiplication operation and element-wise summation operation.  As for scale operation, one weight corresponds to one feature-map. In order to calculate the gradient of scale, we have to perform the per-feature-map summation on the product of top_diff and x_diff.

**Comment by haoLiu1990** [comment]
Thanks for the answer! I'm still a little confused.

Suppose that tid=0, 

for (int j = tid; j < spatial_dim; j += blockDim.x) {
    int offset = blockIdx.x * spatial_dim + j;
    buffer[tid] += top_diff[offset] * x_data[offset];
}

after the previous piece of code,

buffer[0] = the per-feature-map summation on the product of top_diff and x_data.

The value of buffer[0] is changed by the following code.

for (int i = blockDim.x / 2; i > 0; i >>= 1) {
    if (tid < i) {
      buffer[threadIdx.x] += buffer[threadIdx.x + i];
    }
    __syncthreads();
  }

The gradient of scale for a particular feature map should be the per-feature-map summation on the product of top_diff and x_data.

That's the reason why I think the following should be commented out.

for (int i = blockDim.x / 2; i > 0; i >>= 1) {
    if (tid < i) {
      buffer[threadIdx.x] += buffer[threadIdx.x + i];
    }
    __syncthreads();
  }

**Comment by hujie-frank** [comment]
I got your point, and there are some mistakes you made. The __shared__ buffer vector is independent for each channel. Suppose that Z = top_diff * x_data,  CAFFE_CUDA_NUM_THREADS=512. In the first FOR statement, we accumulate gradient like this: buffer[i] = Z[i] + Z[i+512*1] + Z[i+512*2] + Z[i+512*3] + ... until (i+512*k) greater than the size of x_data. Then, in the second FOR statement, we accumulate all the 
values in buffer[512] to buffer[0] which is the exact per-feature-map summation.

**Comment by haoLiu1990** [comment]
An impressive work. Thanks a lot.
