### ISSUE TITLE
About global average pooling layer

### ISSUE THREAD

**Issue by chinakook** [hujie-frank/SENet#2]
When use SENet to FCN, what does the global average pooling layer behave?

**Comment by hujie-frank** [comment]
We have conducted experiments on Cityscapes Dataset using FCN to validate effectiveness of SE upon segmentation task.  With  same training configurations, SE outperforms  its non-SE counterpart. Additionally, we also assessed  SE on COCO detection task. Similarly, SE achieves great improvement against non-SE.

**Comment by chinakook** [comment]
Thanks.

**Comment by cai-y13** [comment]
@hujie-frank could you please give more detail about how to apply SE on FCN, like in which layer to add the SE modules? Thanks.

**Comment by hujie-frank** [comment]
We apply SE in front half of FCN (down-sample stage) to enhance feature expression.

**Comment by cai-y13** [comment]
Thanks for replying, I will try that. If you don't mind, could you please give me more information about your  experiments on COCO detection task, such as how much improvement you get on the mAP compared with non-SE, and which network you use in the detection task ( still FCN?) and how you apply the SE modules?  Thanks soooo much!!

**Comment by zimenglan-sysu-512** [comment]
hi @hujie-frank,
i have a question, why you put the `global_ave backward op` in `PoolingParameter_PoolMethod_STOCHASTIC` case?

**Comment by hujie-frank** [comment]
@zimenglan-sysu-512  Sorry for that,  I called the function in wrong case and I fixed it just now. Thank you for your attention.
