### ISSUE TITLE
SENet out of GPU memory when trying to fine-tuning.

### ISSUE THREAD

**Issue by shiyemin** [hujie-frank/SENet#20]
Hi,

I modified the deploy prototxt to fine-tune SENet. However, even with a barchsize of 1, i still got out of memory error. Please give some help.
Here are the steps that i used to generate train_val.prototxt:
1. add ImageData layers: mean_value 104, 117, 123, cropsize 224
2. add lr_mult and decay_mult for all conv layers and scale layers
3. remove use_global_stats for all BatchNorm layers
4. add solver.prototxt

Then i train it with "caffe train --solver=solver.prototxt --gpu=all --weights=SENet.caffemodel". But no matter how i modify the prototxt, i still got the memory error.

Caffe: master branch
CuDNN: v7.0

**Comment by hujie-frank** [comment]
We have given some advice in #6.
