### ISSUE TITLE
MXNet version?

### ISSUE THREAD

**Issue by kli-nlpr** [hujie-frank/SENet#23]

**Comment by hujie-frank** [comment]
It's easy to extend the modern networks to their SE counterparts from the official MXNet repository by adding a few common layers which we described in Figure 2.

**Comment by bruinxiong** [comment]
Please refer my codes. https://github.com/bruinxiong/SENet.mxnet

**Comment by hujie-frank** [comment]
@bruinxiong Thanks for your contributions.

**Comment by bruinxiong** [comment]
@hujie-frank  Thanks! I'm interested in your work. I will update my github with other architectures. I'm appreciate if you add my link to your github.

**Comment by HiKapok** [comment]
Hi, I have wrote one Tensorflow version for SE_ResNet and SE_ResNeXt, and the pretrained weights converted from caffe version was also provided. You can use the weights for your other DL taskes. If you are interested, please see [TF_Se_ResNeXt](https://github.com/HiKapok/TF_Se_ResNe_t).
