### ISSUE TITLE
Finetuning from ../model/SE-ResNeXt-101.caffemodel

### ISSUE THREAD

**Issue by robotzheng** [hujie-frank/SENet#24]
I0929 12:02:35.547410  5970 caffe.cpp:155] Finetuning from ../model/SE-ResNeXt-101.caffemodel
I0929 12:02:35.856974  5970 net.cpp:761] Ignoring source layer label_data_1_split
I0929 12:02:35.857090  5970 net.cpp:761] Ignoring source layer conv2_1_1x1_increase/bn_conv2_1_1x1_increase/bn_0_split
I0929 12:02:35.857216  5970 net.cpp:761] Ignoring source layer conv2_2_1x1_increase/bn_conv2_2_1x1_increase/bn_0_split
I0929 12:02:35.857317  5970 net.cpp:761] Ignoring source layer conv2_3_1x1_increase/bn_conv2_3_1x1_increase/bn_0_split
I0929 12:02:35.857544  5970 net.cpp:761] Ignoring source layer conv3_1_1x1_increase/bn_conv3_1_1x1_increase/bn_0_split
I0929 12:02:35.857978  5970 net.cpp:761] Ignoring source layer conv3_2_1x1_increase/bn_conv3_2_1x1_increase/bn_0_split
I0929 12:02:35.858289  5970 net.cpp:761] Ignoring source layer conv3_3_1x1_increase/bn_conv3_3_1x1_increase/bn_0_split
I0929 12:02:35.858595  5970 net.cpp:761] Ignoring source layer conv3_4_1x1_increase/bn_conv3_4_1x1_increase/bn_0_split

what is the "bn_0_split"?

**Comment by hujie-frank** [comment]
Just Like the SE-BN-Inception, there was a Reshape layer to squeeze the dimensions of bn_conv_xx_1x1_increase (i.e [B, C, 1, 1]) to  two dimensions (i.e. [B, C]) as the input fed into the following Scale layer. Then we combined the Scale and Element-wise summation into the Axpy layer which allows the four-dimensional input. So we removed the useless Reshape layer while we released deploy prototxts.
