### ISSUE TITLE
synset words list for your pretrain models

### ISSUE THREAD

**Issue by hengck23** [hujie-frank/SENet#25]
I am trying to perform evaluation of your pretrain models on imagenet. I tested a few images and it seems that you are not following the standard caffe "data/ilsvrc12/synset_words.txt " from "http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz".

Where can i find your synset list?

**Comment by hengck23** [comment]
this synset list seems to work:
https://github.com/Cadene/pretrained-models.pytorch/blob/master/data/imagenet_synsets.txt

**Comment by hujie-frank** [comment]
The synset list above is right.
