### ISSUE TITLE
Is the architecture for the best performing model SENet* described anywhere?

### ISSUE THREAD

**Issue by lwoiceshyn** [hujie-frank/SENet#27]
Is this a new custom architecture you came up with, or is it a variant of ResNext or Inception? 

Thanks.

**Comment by ppwwyyxx** [comment]
https://arxiv.org/pdf/1709.01507.pdf

**Comment by lwoiceshyn** [comment]
I've read through the paper, and I understand how the module works and is
implemented into existing architectures.

I'm just wondering which architecture the SENet* is, which is the best
performing model in the repository, since I can't seem to find that
mentioned anywhere.

**Comment by hujie-frank** [comment]
The SENet* is one of the architectures which we used in the ILSVRC 2017 Image Classification task. The details are described in Appendix A. at the end of the paper.

**Comment by lwoiceshyn** [comment]
Thanks, didn't see that!
