### ISSUE TITLE
any pretrained models for mxnet?

### ISSUE THREAD

**Issue by iFighting** [hujie-frank/SENet#28]
any pretrained models for mxnet?
i try to convert the caffe model to mxnet model
but there is a new layer,do you have any pretrain model for mxent

**Comment by hujie-frank** [comment]
We do not have pretrained models for MXNet. You can convert the Caffe model to MXNet model easily as the new layer is a combination of Scale layer and Element-wise Layer which have no parameters. Maybe you can refer to the definition of SENets of [third-party re-implementation](https://github.com/hujie-frank/SENet#third-party-re-implementations) for MXNet.
