### ISSUE TITLE
where have you use your axpy_layer

### ISSUE THREAD

**Issue by Jade999** [hujie-frank/SENet#29]
Hi, I didn't find where you have put your axpy_layer in prototxt, is it replaced by "Scale" layer？

**Comment by hujie-frank** [comment]
We use the axpy_layer in all residual-like architectures (e.g. SE-ResNet and SE-ResNeXt ) as the axpy_layer is a combination of consecutive operations channel-wise scale and element-wise summation. You can certainly find them in the corresponding prototxt.  But it is not necessary for the architectures which have no residual structures (e.g. SE-BN-Inception).

**Comment by Jade999** [comment]
Thank you for your answer, I am just using the SE-BN-Incpetion 。。。
