### ISSUE TITLE
About group convolution in SENet

### ISSUE THREAD

**Issue by suzhenghang** [hujie-frank/SENet#3]
Thanks for sharing your great work, amazing. By the way, do you have some optimization on the group convolution in Caffe? The SENet may suffer memory or speed problems.

**Comment by hujie-frank** [comment]
You can use cuDNN_v7 which conducted great optimization on group convolution. And also the repository https://github.com/yonghenglh6/DepthwiseConvolution.git supports more efficient implementation on depth-wise convolution in Caffe. 

 Actually, as for SENet*,  we trained it using unpublished self-designed distributed training system optimised with significant memory optimization.  I suggest using [MXNet](https://mxnet.incubator.apache.org/index.html) to train such large model as the standard Caffe does little work in memory optimization.

**Comment by suzhenghang** [comment]
@hujie-frank    Ok, many thanks for your suggestions.
