### ISSUE TITLE
Difference between SE-ResNeXt-101 and SENet

### ISSUE THREAD

**Issue by baoruxiao** [hujie-frank/SENet#34]
Hi Hujie,

I wonder what is the architectural difference between SE-ResNeXt-101 and SENet, I have OOM issue with SENet and it almost require 7G to initialize the network, but SE-ResNeXt-101 only need <3G. 
Why there is hug memory usage difference?

Please help.

Thanks,
Ruxiao

**Comment by hujie-frank** [comment]
SENet is constructed by integrating SE blocks to a modified version of the 64x4d ResNeXt-152., so the model size and computation are much bigger than SE-ResNeXt-101. More details about SENet are described in Appendix A. of the [paper](https://arxiv.org/pdf/1709.01507.pdf).
