### ISSUE TITLE
how to add axpy layer to caffe

### ISSUE THREAD

**Issue by haoxuhao** [hujie-frank/SENet#35]

**Comment by hujie-frank** [comment]
1. Download the [axpy.hpp](https://github.com/hujie-frank/SENet/blob/master/include/caffe/layers/axpy_layer.hpp) to folder 'caffe-master/include/caffe/layers/'.
2. Download the [axpy.cpp](https://github.com/hujie-frank/SENet/blob/master/src/caffe/layers/axpy_layer.cpp) and [axpy.cu](https://github.com/hujie-frank/SENet/blob/master/src/caffe/layers/axpy_layer.cu) to folder 'caffe-master/src/caffe/layers/'.

**Comment by wibimaster** [comment]
We have to rebuild caffe after that ?
Thanks !

**Comment by mrgransky** [comment]
how do we solve this problem in case `caffe-gpu` is installed via anaconda?

**Comment by Raychen0617** [comment]
> how do we solve this problem in case `caffe-gpu` is installed via anaconda?

Hi, I meet the same problem, did you figure out the solution?
