### ISSUE TITLE
Can not find fc-layer in SE blocks

### ISSUE THREAD

**Issue by longmao-yiran** [hujie-frank/SENet#36]
Hi Hujie,

First of all thank you open your code,In your introduction,you use two fc-layer in SE block,but in prototxt,I find that you use two conv-layer with 1*1 kernel size. Is this a improvement? If yes ,is this improved performance to compared with the fc-layer.

Please help.

Thanks,
Totoro

**Comment by hujie-frank** [comment]
This is a duplicate issue, please refer to #16.
