### ISSUE TITLE
Augmentation

### ISSUE THREAD

**Issue by liu666666** [hujie-frank/SENet#38]
Thanks for the wonderful job! @hujie-frank 
Could you please share the code that implement the augmentation,such as Aspect Ratio ,Random Rotation, and Pixel Jitter. 
Thank you in advance!

**Comment by hujie-frank** [comment]
As for Aspect Ratio, you can refer to the function **RandomSizedCrop** in [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua).
As for Rotation, you can call OpenCV function **cv::getRotationMatrix2D**.
As for Pixel Jitter, you can generate N (height\*width\*channel) random values range from -20~20, then add to the corresponding pixel.
