### ISSUE TITLE
Some doubts in baselines accuracy

### ISSUE THREAD

**Issue by erdollar** [hujie-frank/SENet#39]
According to your paper: single-crop error rates (%) on the ImageNet validation set .

![default](https://user-images.githubusercontent.com/20589365/34248622-c516c554-e671-11e7-82ba-494f1c40fe77.PNG)

However, I found accuracy in [Resnet](https://arxiv.org/abs/1512.03385)  that is different from your accuracy.
![default](https://user-images.githubusercontent.com/20589365/34248686-f74ba7ec-e671-11e7-8bad-3101e9a80745.PNG)

And I am confused about what's meaning of 

> original  

>re-implementation

thanks.

**Comment by ppwwyyxx** [comment]
The second picture shows 10-crop error rate.

**Comment by erdollar** [comment]
![image](https://user-images.githubusercontent.com/20589365/34251303-9df08d1c-e67a-11e7-963c-2902b0092d7b.png)
According to [Resnet](https://arxiv.org/abs/1512.03385),Resnet-50  error rates (%, 10-crop testing) on ImageNet validation is 
>top5 22.85   top1  6.71
Not equal to  SE-Resnet
![image](https://user-images.githubusercontent.com/20589365/34251451-1e08589a-e67b-11e7-8c81-45efbb77e03e.png)
Thank you for your patience.

**Comment by hujie-frank** [comment]
Here, we report the single-crop results. The ResNet table presents the 10-crop results.

**Comment by erdollar** [comment]
emm，Thanks.

**Comment by erdollar** [comment]
Resnet accuracy data on ImageNet is public ?   I can't found single-crop results (just like SE-Resnet paper shows ) in Resnet papers.

**Comment by GangSunLion** [comment]
Please see the ResNet github, https://github.com/KaimingHe/deep-residual-networks

**Comment by erdollar** [comment]
thanks ：)
