### ISSUE TITLE
HOW to set the caffe.proto?

### ISSUE THREAD

**Issue by chunniunai220ml** [hujie-frank/SENet#42]
i have add all layers,and make success,but 
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Axpy (known types: AbsVal, Accuracy, ......WindowData)
*** Check failure stack trace: ***
so HOW to set the caffe.proto?

**Comment by hujie-frank** [comment]
You don't need to set caffe.proto as there is no extra param setting required in Axpy layer.

**Comment by hujie-frank** [comment]
It's quite weird. Maybe you can make clean and make again.  By the way, did you solve this issue?
