### ISSUE TITLE
Enough memory for training but not enough memory for testing?

### ISSUE THREAD

**Issue by SingL3** [hujie-frank/SENet#50]
Greeting!
I am training SE-Resnet-50, and I have enough GPU memory for training.
But when I am trying to do testing with the same config, I got out of memory error.
I am confused, do SE need more memory in testing phase than training?

**Comment by hujie-frank** [comment]
No,  SE doesn't need more memory in testing phase.  Maybe the batch size in testing is set too large, or the memory is not thoroughly released after training stage.
