### ISSUE TITLE
Have you try SE-Densenet?

### ISSUE THREAD

**Issue by John1231983** [hujie-frank/SENet#51]
Thanks for great network. I found that Se module is general and it can apply to any kind of network. You have tried with the state of the art network but i did not find it apply to densenet. Could you try with se-densenet and what is your performance with it?

**Comment by John1231983** [comment]
@hujie-frank : Could you please look at the issue. For resnet, it is clear to add the se module before sum, but for densenet, which position could we add se module (after or before transition?)? or somewhere?

**Comment by lishen-shirley** [comment]
@John1231983 Thank you for your interest in the work. We haven't developed the experiments on the Densenet architecture. You might refer to these two papers ("BAM: Bottleneck Attention Module"  and "Convolutional Neural Networks with Alternately Updated Clique") which integrated the SE module (or an SE variant) into Densenet (or Densenet variant).

**Comment by snorlaxse** [comment]
I have the issue.  Have you solved it ? @John1231983 
Your help is very important to me. I hope to receive your reply.
