### ISSUE TITLE
train

### ISSUE THREAD

**Issue by zq130320339** [hujie-frank/SENet#52]
Solving...
F0616 13:59:44.988385 16022 math_functions.cu:79] Check failed: error == cudaSuccess (74 vs. 0)  misaligned address

how to solve the problem?

**Comment by hujie-frank** [comment]
Sorry, I haven't encountered this problem yet. Maybe you can upgrade the CUDA driver.

**Comment by hawl666** [comment]
It's your computer video memory is insufficient @zq130320339
