### ISSUE TITLE
test problem about class

### ISSUE THREAD

**Issue by elesun2018** [hujie-frank/SENet#54]
**class.sh**
#!/bin/sh
/home/sun/SENet-master-hujie/caffe/build/examples/cpp_classification/classification.bin \
/home/sun/SENet-master-hujie/models/SE-BN-Inception.prototxt \
/home/sun/SENet-master-hujie/models/SE-BN-Inception.caffemodel \
imagenet_mean.binaryproto \
synset_words.txt \
car.jpg

sun@ubuntu:~/SENet-master-hujie/demo$ sh class.sh 
---------- Prediction for car.jpg ----------
0.3955 - "n02114855 coyote, prairie wolf, brush wolf, Canis latrans"
0.2930 - "n02115641 dingo, warrigal, warragal, Canis dingo"
0.1158 - "n03388043 fountain"
0.0357 - "n02120505 grey fox, gray fox, Urocyon cinereoargenteus"
0.0200 - "n02113624 toy poodle"

why, thanks

**Comment by hujie-frank** [comment]
Please refer to issue #5 .
