### ISSUE TITLE
About SE-ResNeXt-101 (32 x 4d) 

### ISSUE THREAD

**Issue by suzhenghang** [hujie-frank/SENet#6]
Hi @hujie-frank ,
         Have you runned SE-ResNeXt-101 (32 x 4d)  on caffe before? No matter how many GPUs I use, the memory problem is serious. SE-ResNeXt-50 is Ok.

**Comment by hujie-frank** [comment]
Actually, the standard Caffe does little work on memory optimization. You'd better find another version conducted much memory optimization (maybe you can try [this](https://github.com/yjxiong/caffe/tree/mem) ) or use more efficient training system, such as MXNet.

**Comment by chenbinghui1** [comment]
The caffe version of memory optimization (https://github.com/yjxiong/caffe/tree/mem) has some issues when using simase network. But I don't know why, maybe there are some bugs in the implementations.
