### ISSUE TITLE
Why SENet-ResNet-50 model size is much bigger than ResNet-50 

### ISSUE THREAD

**Issue by haikuoyao** [hujie-frank/SENet#60]
`
 SE- ResNet-50 introduces ∼2.5 million additional parameters beyond the ∼25 million parametersrequired by ResNet-50, corresponding to a ∼10% increase. 
`
Accroding the paper, parameters only increases 10% than ResNet. 
But why SENet-ResNet-50 model size(100M) is much bigger than ResNet-50(20M)?
Thanks.

**Comment by haikuoyao** [comment]
Solved. Sorry

**Comment by chdsm2224** [comment]
Sorry to bother you, can you tell me the reason?
