### ISSUE TITLE
About the label list of ilsvrc2017

### ISSUE THREAD

**Issue by xhappy** [hujie-frank/SENet#63]
I'm sorry that I have a question which is not related with this network, but I really don't find the label list of ilsvrc2017 dataset, so could you please deliver the label list to me? Thanks in advance.

**Comment by hujie-frank** [comment]
[ILSVRC2012_2017_CLS_Mapping_.txt](https://github.com/hujie-frank/SENet/files/2704824/ILSVRC2012_2017_CLS_Mapping_.txt)
Here is a mapping from  ILSVRC2012 label to ILSVRC2017 label.  Notably, the starting index in  ILSVRC2017 is 1, rather 0.
