### ISSUE TITLE
Different error rates for baseline Resnet-50 in Table 2 and Table (10,13)

### ISSUE THREAD

**Issue by pratikm141** [hujie-frank/SENet#65]
Different error rates have been mentioned for 

baseline Resnet-50:
**24.8** in **Table 2** and **23.30** in **Table 10,13**

SE-Resnet-50:
**23.29** in **Table 2** and **22.28** in **Table 10,11,12,13,14,15**

Is this a typo or am I missing something

**Comment by lishen-shirley** [comment]
The ablation studies in the journal extension (including table 10 to 15) are performed on different training schedules compared to the table 2. Please see the section 5.1 and the first paragraph of section 6 for details.
