### ISSUE TITLE
 Check failed: ExactNumBottomBlobs() == bottom.size() (3 vs. 2) Axpy Layer takes 3 bottom blob(s) as input.

### ISSUE THREAD

**Issue by rmxhhh** [hujie-frank/SENet#67]
Hi,I want to add senet to faster r-cnn(caffe),but there is an erro when i run the model ," Check failed: ExactNumBottomBlobs() == bottom.size() (3 vs. 2) Axpy Layer takes 3 bottom blob(s) as input."Can you tell me where is wrong?Thank you very much,it's very important for me.

**Comment by hujie-frank** [comment]
The Axpy layer requires 3 inputs but you seem using 2 inputs only.
