### ISSUE TITLE
Question on top-1 error

### ISSUE THREAD

**Issue by Sirius083** [hujie-frank/SENet#72]
I saw the original paper top1 error rate for resnet-50 on imagenet is  20.74%
[Deep residual learning for image recognition]
the paper site the original resnet-50 on imagenet is 24.7%(Table 2 row 1)
Why there is a difference ?
Thanks in advance

**Comment by hujie-frank** [comment]
The original paper doesn't use RandomResizedCrop data augmentation which can substantially improve accuracy.

**Comment by lishen-shirley** [comment]
20.74% is the single-model error with multi-scale augmentation (you can find more information in the ``Implementation" section of the ResNet paper. 24.7% single-crop error is obtained from the official implementation: https://github.com/KaimingHe/deep-residual-networks.
