### ISSUE TITLE
关于Repository的疑问和se_resnet50

### ISSUE THREAD

**Issue by my-hello-world** [hujie-frank/SENet#73]
感谢您的项目思想。有些问题想请教。

1. 您说到：

> > Caffe. SE-mudolues are integrated with a modificated ResNet-50 using a stride 2 in the 3x3 convolution instead of the first 1x1 convolution which obtains better performance: Repository.

这个我去看了他的（https://github.com/shicai/SENet-Caffe）.prototxt文件，并没有改变啊.

2. 另外，关于se_resnet50，我觉得两个FC的参数太大了，想换成两个1*1卷积，您有试过吗？和fc比精度怎样呢？

盼望回复~
感谢！

**Comment by hujie-frank** [comment]
1. For instance,  the layer named "conv3_1/x2" in [https://github.com/shicai/SENet-Caffe](https://github.com/shicai/SENet-Caffe) is a convolutional layer with stride 2, but in original resnet-50, the downsampling is conducted at the layer 'conv3_1/x1'.
2. Here, using two FC layers and two convolutional layers are exactly equivalent. In our implementation, we employ convolutional layers.
