### ISSUE TITLE
down and up weight initialization

### ISSUE THREAD

**Issue by royhj** [hujie-frank/SENet#74]
Hello,
Thank you for your great work and paper.

I have a little question about weight initialization:
In the SE block, how are the fully connected down (squeeze) and up (excite) weights initialized?
I couldn't find the answer in the paper or the implementation here.

Thanks you!

**Comment by hujie-frank** [comment]
The weight initialization about two FC layers is not mattered, you can use 'msra' initialization or gaussian initialization with std 0.01. Actually, it does not affect results.

**Comment by royhj** [comment]
Thank you @hujie-frank
