### ISSUE TITLE
Can SE blocks be used for regression tasks?

### ISSUE THREAD

**Issue by Ericjiejie** [hujie-frank/SENet#76]
Hi,@lishen-shirley
Can SE blocks be used for regression tasks? For example, hand posture estimation.

**Comment by lishen-shirley** [comment]
SE blocks can be regarded as a basic component for learning representations with convolutional network architectures. As we know, the module or the idea has been used in a wide range of visual tasks, such as classification, detection, segmentation, depth-estimation and super-resolution though we mainly evaluated it in classification tasks.
