### ISSUE TITLE
if data layer need scale?

### ISSUE THREAD

**Issue by xuanyuyt** [hujie-frank/SENet#79]
when I use caffemodel to test, I find may be I need scale  parameter for data layer, so what is scale?
# mean_value: 104, 117, 123
layer { 
  name: "data"
  type: "Input"
  top: "data"
  input_param: {
    shape: {
      dim: 1 
      dim: 3 
      dim: 224 
      dim: 224
    }
  }
}

**Comment by hujie-frank** [comment]
In the training stage, we just perform mean subtraction for each channel and none of scaling strategy used in the data layer.
