### ISSUE TITLE
hello,i want ask a question

### ISSUE THREAD

**Issue by lijie-vipl-ict** [hujie-frank/SENet#8]
thank you for realeasing  your code.
now,how can I get the SE-ResNet-152.prototxt to the train_SE-ResNet-152.prototxt(train version)?
i'm looking forward your answer,thank you.

**Comment by hujie-frank** [comment]
It's easy to generate train prototxt by inserting lr_mult and decay_mult setting to all convolutional and BatchNorm layers and initialing weights of convolutional layers with "msra" method.

**Comment by lijie-vipl-ict** [comment]
多谢，大佬。i'm a newer student,thank you!

**Comment by biyaa** [comment]
where should I insert lr_mult in a  BatchNorm layer? should I insert in scale_param?

**Comment by hujie-frank** [comment]
@biyaa You can refer to the third-party reimplementation to insert the settings: [Repository](https://github.com/shicai/SENet-Caffe)

**Comment by biyaa** [comment]
is that correct? (BN-Inception)

[SE-BN-Inception_t2.proto.txt](https://github.com/hujie-frank/SENet/files/1313519/SE-BN-Inception_t2.proto.txt)

`

**Comment by hujie-frank** [comment]
Yes, it is correct and you'd better add another `param { lr_mult: 1  decay_mult: 0 } ` for bias term in Scale layer after each BatchNorm layer.

**Comment by biyaa** [comment]
thank you
