### ISSUE TITLE
the differences with the third-party caffe impl.

### ISSUE THREAD

**Issue by yuzcccc** [hujie-frank/SENet#9]
You mentioned the conv used are slightly different(3x3 vs. 1x1). However, by comparing your model's prototxt and shicai's, I could not find the difference, could you please point it out more specifically? e.g., the name of the difference layer. Thanks very much!

**Comment by hujie-frank** [comment]
Shicai uses a stride 2 in 3x3 convolution (e.g. conv3_1/x2, conv4_1/x2, conv5_1/x2) at the beginning of each stage, which follows the setting of [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch), while we employs a stride 2 in first  1x1 convolution (e.g. conv3_1_1x1_reduce,  conv4_1_1x1_reduce, conv5_1_1x1_reduce) , matching the standard ResNet for a fair comparison.

**Comment by yuzcccc** [comment]
@hujie-frank I see, thanks for the explanation : )
